# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status_notification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status_notification.proto',
  package='StatusNotification',
  syntax='proto2',
  serialized_pb=_b('\n\x19status_notification.proto\x12\x12StatusNotification\"\x97\x02\n\x19StatusNotificationRequest\x12\x11\n\ttimestamp\x18\x01 \x02(\t\x12^\n\x0f\x63onnectorStatus\x18\x02 \x02(\x0e\x32\x45.StatusNotification.StatusNotificationRequest.ConnectorStatusEnumType\x12\x0e\n\x06\x65vseId\x18\x03 \x02(\x05\x12\x13\n\x0b\x63onnectorId\x18\x04 \x02(\x05\"b\n\x17\x43onnectorStatusEnumType\x12\r\n\tAvailable\x10\x00\x12\x0c\n\x08Occupied\x10\x01\x12\x0c\n\x08Reserved\x10\x02\x12\x0f\n\x0bUnavailable\x10\x03\x12\x0b\n\x07\x46\x61ulted\x10\x04\"\x1c\n\x1aStatusNotificationResponse')
)



_STATUSNOTIFICATIONREQUEST_CONNECTORSTATUSENUMTYPE = _descriptor.EnumDescriptor(
  name='ConnectorStatusEnumType',
  full_name='StatusNotification.StatusNotificationRequest.ConnectorStatusEnumType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Available', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Occupied', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Reserved', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unavailable', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Faulted', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=231,
  serialized_end=329,
)
_sym_db.RegisterEnumDescriptor(_STATUSNOTIFICATIONREQUEST_CONNECTORSTATUSENUMTYPE)


_STATUSNOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='StatusNotificationRequest',
  full_name='StatusNotification.StatusNotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='StatusNotification.StatusNotificationRequest.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectorStatus', full_name='StatusNotification.StatusNotificationRequest.connectorStatus', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='evseId', full_name='StatusNotification.StatusNotificationRequest.evseId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectorId', full_name='StatusNotification.StatusNotificationRequest.connectorId', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUSNOTIFICATIONREQUEST_CONNECTORSTATUSENUMTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=329,
)


_STATUSNOTIFICATIONRESPONSE = _descriptor.Descriptor(
  name='StatusNotificationResponse',
  full_name='StatusNotification.StatusNotificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=359,
)

_STATUSNOTIFICATIONREQUEST.fields_by_name['connectorStatus'].enum_type = _STATUSNOTIFICATIONREQUEST_CONNECTORSTATUSENUMTYPE
_STATUSNOTIFICATIONREQUEST_CONNECTORSTATUSENUMTYPE.containing_type = _STATUSNOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['StatusNotificationRequest'] = _STATUSNOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['StatusNotificationResponse'] = _STATUSNOTIFICATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusNotificationRequest = _reflection.GeneratedProtocolMessageType('StatusNotificationRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSNOTIFICATIONREQUEST,
  __module__ = 'status_notification_pb2'
  # @@protoc_insertion_point(class_scope:StatusNotification.StatusNotificationRequest)
  ))
_sym_db.RegisterMessage(StatusNotificationRequest)

StatusNotificationResponse = _reflection.GeneratedProtocolMessageType('StatusNotificationResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSNOTIFICATIONRESPONSE,
  __module__ = 'status_notification_pb2'
  # @@protoc_insertion_point(class_scope:StatusNotification.StatusNotificationResponse)
  ))
_sym_db.RegisterMessage(StatusNotificationResponse)


# @@protoc_insertion_point(module_scope)
